/**
 * lib/pdf/layout.ts
 * Page geometry constants, text utilities, sanitization helpers, and structural layout elements
 * (page footer, section divider, and running header) shared across all PDF pages.
 */

import { COLORS } from "./tokens";
import { filledRect, filledRoundRect, hLine, textColor, drawBrandLogo } from "./primitives";

// ─── Page Geometry ───────────────────────────────────────────────────────────

export const PAGE_W    = 210;   // A4 width in mm
export const PAGE_H    = 297;   // A4 height in mm
export const MARGIN    = 15;    // Left/right margin in mm
export const CONTENT_W = PAGE_W - MARGIN * 2;
export const FOOTER_H  = 12;

// ─── Text Utilities & Sanitization ───────────────────────────────────────────

/**
 * Strips markdown syntax (links, code formatting, bold, italics) into clean plain text.
 */
export function cleanText(s: string | null | undefined): string {
  if (!s) return "";
  return s
    // Convert markdown links [text](url) -> text
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    // Remove backticks
    .replace(/`/g, "")
    // Remove bold/italics markers
    .replace(/[*_]{1,3}([^*_]+)[*_]{1,3}/g, "$1")
    // Replace non-standard unicode mathematical symbols with safe ASCII equivalents
    .replace(/[≤]/g, "<=")
    .replace(/[≥]/g, ">=")
    .replace(/[−–—]/g, "-")
    .replace(/[“”]/g, '"')
    .replace(/[‘’]/g, "'")
    .replace(/[…]/g, "...")
    .trim();
}

/** Truncates a string cleanly without breaking words abruptly. */
export function trunc(s: string, maxChars: number): string {
  const cleaned = cleanText(s);
  if (cleaned.length <= maxChars) return cleaned;
  return cleaned.slice(0, maxChars - 3) + "...";
}

/**
 * Wraps clean text into lines that fit within `maxW` mm at the given font size.
 */
export function wrapText(doc: any, text: string, maxW: number, fontSize: number): string[] {
  doc.setFontSize(fontSize);
  return doc.splitTextToSize(cleanText(text), maxW);
}

// ─── Structural Elements ─────────────────────────────────────────────────────

/**
 * Draws the branded page footer at the bottom of the current page.
 */
export function drawFooter(doc: any, pageNum: number, totalPages: number) {
  // Thin brand-accent rule above the band
  filledRect(doc, 0, PAGE_H - FOOTER_H - 0.4, PAGE_W, 0.4, COLORS.brand);

  // Dark footer band
  filledRect(doc, 0, PAGE_H - FOOTER_H, PAGE_W, FOOTER_H, COLORS.obsidian);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.5);
  textColor(doc, COLORS.faint);
  doc.text("Generated by AuditHQ  ·  swiftaudithq.vercel.app", MARGIN, PAGE_H - 4.5);

  doc.setFont("helvetica", "bold");
  textColor(doc, COLORS.ghostWhite);
  doc.text(`PAGE ${pageNum} OF ${totalPages}`, PAGE_W / 2, PAGE_H - 4.5, { align: "center" });

  doc.setFont("helvetica", "normal");
  textColor(doc, COLORS.faint);
  doc.text("CONFIDENTIAL AUDIT REPORT", PAGE_W - MARGIN, PAGE_H - 4.5, { align: "right" });
}

/**
 * Draws a clean, modern section divider with a brand-accent pill indicator.
 * Avoids heavy dark full-bleed strips so document structure remains clear and readable.
 * @returns The new `y` position for content below this section header.
 */
export function drawSectionDivider(doc: any, y: number, title: string, subtitle?: string): number {
  // Left vertical indicator pill
  filledRoundRect(doc, MARGIN, y + 0.5, 2.5, 8.5, 0.8, COLORS.brand);

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  textColor(doc, COLORS.ink);
  doc.text(title, MARGIN + 5.5, y + 6.8);

  // Subtitle
  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.8);
    textColor(doc, COLORS.muted);
    doc.text(subtitle, PAGE_W - MARGIN, y + 6.8, { align: "right" });
  }

  // Subtle hairline rule below header
  hLine(doc, MARGIN, y + 10.5, PAGE_W - MARGIN, COLORS.border, 0.25);

  return y + 15;
}

/**
 * Draws the clean running header (used on pages 2–4).
 * Light background with a brand accent stripe and vector logo mark.
 */
export function drawPageMiniHeader(
  doc: any,
  testId: string | number,
  hostname: string,
  rightLabel: string
) {
  // Top brand stripe
  filledRect(doc, 0, 0, PAGE_W, 1.5, COLORS.brand);

  // Small vector brand icon
  drawBrandLogo(doc, MARGIN, 4, { isDark: false, showText: false, size: 5 });

  // Brand Name
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  textColor(doc, COLORS.ink);
  doc.text("AuditHQ", MARGIN + 7, 7.8);

  // Telemetry details
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  textColor(doc, COLORS.muted);
  doc.text(`·  ${trunc(hostname, 45)}  ·  Audit #${testId}`, MARGIN + 21.5, 7.8);

  // Right section label
  doc.setFont("helvetica", "bold");
  textColor(doc, COLORS.brand);
  doc.text(rightLabel, PAGE_W - MARGIN, 7.8, { align: "right" });

  // Subtle hairline separator below running header
  hLine(doc, MARGIN, 11.5, PAGE_W - MARGIN, COLORS.border, 0.25);
}
